language: c
notifications:
  email: false
install:
      - sudo apt-get update
      - sudo apt-get install python3 python3-pip python3-serial pylint unzip
      - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
      - sleep 3
      - export DISPLAY=:1.0
      - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
      - tar xf arduino-1.8.5-linux64.tar.xz
      - sudo mv arduino-1.8.5 /usr/local/share/arduino
      - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/
      #- curl -s https://api.github.com/repos/esp8266/Arduino/releases/latest | grep "browser_download_url.*zip" | cut -d '"' -f 4 | wget -qi -
      #- unzip esp8266*.zip
      #- rm esp8266*.zip
      #- mkdir ~/Arduino
      #- mkdir ~/Arduino/hardware
      #- mv esp8266* ~/Arduino/hardware/esp8266



script:
  - arduino --verify --board arduino:avr:uno $PWD/flightcomputer/flightcompunter.ino
  - arduino --verify --board arduino:avr:uno $PWD/GNCConsole/GNC_Radio/GNC_Radio.ino
  - pylint --errors-only $PWD/GNCConsole/baseStation.py
